#!/bin/bash

show_clean_help() {
    echo "Usage: mo clean [OPTIONS]"
    echo ""
    echo "Clean up disk space by removing caches, logs, and temporary files."
    echo ""
    echo "Options:"
    echo "  --dry-run, -n     Preview cleanup without making changes"
    echo "  --whitelist       Manage protected paths"
    echo "  --log, -l         Show last session: what was cleaned and where"
    echo "  --log --all       Show full path list from last session"
    echo "  --debug           Show detailed operation logs"
    echo "  -h, --help        Show this help message"
}

show_installer_help() {
    echo "Usage: mo installer [OPTIONS]"
    echo ""
    echo "Find and remove installer files (.dmg, .pkg, .iso, .xip, .zip)."
    echo ""
    echo "Options:"
    echo "  --dry-run         Preview installer cleanup without making changes"
    echo "  --debug           Show detailed operation logs"
    echo "  -h, --help        Show this help message"
}

show_optimize_help() {
    echo "Usage: mo optimize [OPTIONS]"
    echo ""
    echo "Check and maintain system health, apply optimizations."
    echo ""
    echo "Options:"
    echo "  --dry-run         Preview optimization without making changes"
    echo "  --whitelist       Manage protected items"
    echo "  --debug           Show detailed operation logs"
    echo "  -h, --help        Show this help message"
}

show_touchid_help() {
    echo "Usage: mo touchid [COMMAND]"
    echo ""
    echo "Configure Touch ID for sudo authentication."
    echo ""
    echo "Commands:"
    echo "  enable            Enable Touch ID for sudo"
    echo "  disable           Disable Touch ID for sudo"
    echo "  status            Show current Touch ID status"
    echo ""
    echo "Options:"
    echo "  --dry-run         Preview Touch ID changes without modifying sudo config"
    echo "  -h, --help        Show this help message"
    echo ""
    echo "If no command is provided, an interactive menu is shown."
}

show_uninstall_help() {
    echo "Usage: mo uninstall [OPTIONS]"
    echo ""
    echo "Interactively remove applications and their leftover files."
    echo ""
    echo "Options:"
    echo "  --dry-run         Preview app uninstallation without making changes"
    echo "  --whitelist       Not supported for uninstall (use clean/optimize)"
    echo "  --debug           Show detailed operation logs"
    echo "  -h, --help        Show this help message"
}

# Structured tree view of all commands, subcommands, and flags.
# Called by show_help() in the main mole entrypoint.
show_help_tree() {
    local T; T=$(printf '\xe2\x94\x9c\xe2\x94\x80\xe2\x94\x80')
    local E; E=$(printf '\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80')

    echo ""
    printf "%s%s%s\n" "$BLUE" "COMMANDS" "$NC"
    printf "  %smo%s                              Interactive main menu\n" "$GREEN" "$NC"
    echo ""

    printf "  %sCleanup & Disk%s\n" "$BLUE" "$NC"
    echo ""
    printf "  %smo clean%s                         Free up disk space\n" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview cleanup\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--whitelist%s                 Manage protected caches\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--log, -l%s                   Show last session report\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--debug%s                     Verbose logs\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo uninstall%s                     Remove apps completely\n" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview uninstall\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--debug%s                     Verbose logs\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo purge%s                         Remove old project artifacts\n" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview purge actions\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--paths%s                     Configure scan directories\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--debug%s                     Verbose logs\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo installer%s                     Find and remove installer files\n" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview installer cleanup\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--debug%s                     Verbose logs\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo analyze%s %s[path]%s               Explore disk usage\n" "$GREEN" "$NC" "$GRAY" "$NC"
    printf "  %s %s %s/Volumes%s                    Analyze external drives\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""

    printf "  %sSystem%s\n" "$BLUE" "$NC"
    echo ""
    printf "  %smo optimize%s                      Check and maintain system\n" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run%s                   Preview optimization\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--whitelist%s                 Manage protected items\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--debug%s                     Verbose logs\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo defaults%s                      Tune macOS settings\n" "$GREEN" "$NC"
    printf "  %s %s %s--list, -l%s                  Show all settings and state\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--all, -a%s                   Enable all power-user settings\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--reset, -r%s                 Restore all original values\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview changes\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo login%s                         Manage startup items\n" "$GREEN" "$NC"
    printf "  %s %s %s--list, -l%s                  List all startup items\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--orphans, -o%s               Show orphaned agents only\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview changes\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo touchid%s %s[enable|disable|status]%s\n" "$GREEN" "$NC" "$GRAY" "$NC"
    printf "                                    Configure Touch ID for sudo\n"
    printf "  %s %s %senable%s                      Enable Touch ID for sudo\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %sdisable%s                     Disable Touch ID for sudo\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %sstatus%s                      Show current state\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview changes\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""

    printf "  %sDiagnostics%s\n" "$BLUE" "$NC"
    echo ""
    printf "  %smo status%s                        Monitor system health (TUI)\n" "$GREEN" "$NC"
    echo ""
    printf "  %smo network%s                       Full network report\n" "$GREEN" "$NC"
    printf "  %s %s %s--ui, -u%s                    Interactive dashboard (TUI)\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--quick, -q%s                 Interfaces + Wi-Fi + LAN only\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--scan, -s%s %s<ip>%s            Deep scan a specific host\n" "$GRAY" "$T" "$GREEN" "$NC" "$GRAY" "$NC"
    printf "  %s %s %s--connections, -c%s           Active connections by process\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--ports, -p%s                 Show listening ports\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--devices, -d%s               LAN device discovery\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--debug%s                     Verbose output\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo security%s                      Run security audit\n" "$GREEN" "$NC"
    printf "  %s %s %s--full, -f%s                  Include Lynis + nmap scans\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview what checks run\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--debug%s                     Show detailed findings\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo privacy%s                       Clean tracking data\n" "$GREEN" "$NC"
    printf "  %s %s %s--scan, -s%s                  Scan only (show sizes)\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--clean, -c%s                 Clean immediately\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview cleanup\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""

    printf "  %sMaintenance%s\n" "$BLUE" "$NC"
    echo ""
    printf "  %smo update%s                        Update to latest version\n" "$GREEN" "$NC"
    printf "  %s %s %s--force, -f%s                 Force reinstall latest stable\n" "$GRAY" "$T" "$GREEN" "$NC"
    printf "  %s %s %s--nightly%s                   Install unreleased main branch\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo remove%s                        Remove Mole from system\n" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview removal\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo completion%s                    Setup shell tab completion\n" "$GREEN" "$NC"
    printf "  %s %s %s--dry-run, -n%s              Preview config changes\n" "$GRAY" "$E" "$GREEN" "$NC"
    echo ""
    printf "  %smo --help%s                        This help\n" "$GREEN" "$NC"
    printf "  %smo --version%s                     Version and system info\n" "$GREEN" "$NC"
    echo ""

    printf "%s%s%s\n" "$BLUE" "GLOBAL OPTIONS" "$NC"
    printf "  %s--debug%s                           Show detailed operation logs\n" "$GREEN" "$NC"
    echo ""
}
